version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: fraud_password
      POSTGRES_DB: fraud_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./sql/rules.sql:/docker-entrypoint-initdb.d/2_rules.sql
    restart: unless-stopped
    command: postgres -c shared_preload_libraries='cube,earthdistance'

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - ./ml:/app/ml
      - ./data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
